CREATE EXTENSION pgtap;

CREATE EXTENSION postgis;
CREATE EXTENSION pgrouting;
CREATE EXTENSION pgcrypto;
CREATE EXTENSION pgsodium;
-- CREATE EXTENSION supabase_vault;

CREATE EXTENSION pgjwt;
CREATE EXTENSION plpgsql_check;
-- CREATE EXTENSION plv8; FIXME (aseipp): nixos/nixpkgs#246702
CREATE EXTENSION rum;
CREATE EXTENSION vector;
CREATE EXTENSION pg_repack;
CREATE EXTENSION pgroonga;

CREATE EXTENSION http;
CREATE EXTENSION pg_graphql;
CREATE EXTENSION pg_jsonschema;
